ALTER TABLE "User" ADD COLUMN "notifAssignments" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "notifEscalations" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "notifDigest" BOOLEAN NOT NULL DEFAULT true;
